spring.application.name=RoleBackend
server.port=8080

spring.datasource.url=jdbc:h2:mem:role_backend_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT Configuration
app.jwt.secret=9B94A42C953DBB1D348E5EA6D76AC83AE4B1278C8229ED4E0FF4E6B4DF9F10AA
app.jwt.expiration-ms=86400000
